# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
    - name: KeywordIntentClassifier
    - name: FallbackClassifier
      threshold: 0.3
      ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
    - name: RulePolicy
